### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.vocabularyregistry#3]
Could we please get a PyPI release when convenient?  There have been a couple of relatively minor but nice-to-have changes (#1, #2) that it would be nice to see released.

**Comment by mgedmin** [comment]
@alga, could you ping @strichter for us?  He's the only PyPI owner for https://pypi.python.org/pypi/zope.vocabularyregistry and doesn't seem to be responding to direct GitHub pings...

**Comment by icemac** [comment]
@strichter Hi, you are still the only one who is allowed to create PyPI releases. Could you please add at least `icemac` as Owner, so I can share the permissions later on?

**Comment by icemac** [comment]
@srichter Thank you for assigning me the owner role, I shared it with @mgedmin and @jamadden. Im am going to cut a release now.

**Comment by icemac** [comment]
Version 1.2.0 is now on PyPI: https://pypi.org/project/zope.vocabularyregistry/1.2.0/
